services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  spring-boot-example:
    container_name: spring-boot-example
    image: munyao/spring-boot-example
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"  # Quotes added for correct syntax
    ports:
      - "8088:8080"
    networks:
      - postgres  # Corrected to use the defined "postgres" network
    depends_on:
      - db
    restart: unless-stopped

  react-example:
    container_name: react-example
    image: munyao/react-example
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - spring-boot-example
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
